# Generated by Django 5.1.1 on 2024-11-14 06:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import stdimage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('general_description', models.TextField(blank=True, null=True)),
                ('social_description', models.TextField(blank=True, null=True)),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='corridors', variations={'large': (1280, 1024), 'medium': (800, 600), 'thumbnail': (350, 350)})),
                ('wards', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('doc_type', models.IntegerField(choices=[(1, 'Existing stepping-stones'), (2, 'Corridor connectors'), (3, 'Transport'), (4, 'Possible stepping-stones'), (5, 'Context'), (6, 'Teaching resources'), (7, 'General document repository')], db_index=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='See https://htmlcolors.com/color-names for an overview of possible color names', max_length=50, null=True)),
                ('meta_data', models.JSONField(blank=True, help_text='Only to be edited if you know what this does - otherwise, please do not change', null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('include_in_site_analysis', models.BooleanField(db_index=True, default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='website.document')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Genera',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', stdimage.models.StdImageField(force_min_size=False, upload_to='pages', variations={'large': (1280, 1024), 'medium': (800, 600), 'thumbnail': (350, 350)})),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_html', models.TextField(blank=True, help_text='Auto-generated - do NOT edit', null=True)),
                ('image', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pages', variations={'large': (1280, 1024), 'medium': (800, 600), 'thumbnail': (350, 350)})),
                ('position', models.PositiveSmallIntegerField(db_index=True)),
                ('slug', models.SlugField(max_length=255)),
                ('format', models.CharField(choices=[('HTML', 'HTML'), ('MARK', 'Markdown'), ('MARK_HTML', 'Markdown and HTML')], max_length=9)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', stdimage.models.StdImageField(force_min_size=False, upload_to='photos', variations={'large': (1280, 1024), 'medium': (800, 600), 'thumbnail': (350, 350)})),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('date', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.event')),
            ],
            options={
                'ordering': ['position', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Redlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=2)),
                ('css', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Redlist',
            },
        ),
        migrations.CreateModel(
            name='SpeciesFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('species_type', models.IntegerField(choices=[(1, 'Animal-friendly'), (2, 'Tolerances/sites'), (3, 'Growth features'), (4, 'Other')], db_index=True, default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('referencespace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.referencespace')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('original', models.JSONField(blank=True, null=True)),
                ('phase_assessment', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Initial ecological and social assessment')),
                ('phase_alienremoval', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Alien removal')),
                ('phase_landscaping', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Landscaping')),
                ('phase_pioneers', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Planting of pioneer species')),
                ('phase_birdsinsects', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Planting of bird and insect species')),
                ('phase_specialists', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Planting of specialist species')),
                ('phase_placemaking', models.IntegerField(choices=[(1, 'Pending'), (2, 'In progress'), (3, 'Completed')], db_index=True, null=True, verbose_name='Placemaking')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('organizations', models.ManyToManyField(blank=True, to='website.organization')),
            ],
            bases=('website.referencespace',),
        ),
        migrations.AddField(
            model_name='referencespace',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencespace', to='website.photo'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.photo'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.language')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('common_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('common_name_xh', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('common_name_af', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('animals', models.JSONField(blank=True, null=True)),
                ('soils', models.JSONField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('propagation_seed', models.TextField(blank=True, null=True)),
                ('propagation_cutting', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='website.family')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='website.genus')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_species', to='website.photo')),
                ('redlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.redlist')),
                ('features', models.ManyToManyField(blank=True, related_name='species', to='website.speciesfeatures')),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.species'),
        ),
        migrations.CreateModel(
            name='VegetationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('redlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.redlist')),
                ('spaces', models.ManyToManyField(blank=True, limit_choices_to={'source_id': 983172}, to='website.referencespace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='species',
            name='vegetation_types',
            field=models.ManyToManyField(blank=True, related_name='species', to='website.vegetationtype'),
        ),
        migrations.AddField(
            model_name='photo',
            name='garden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.garden'),
        ),
        migrations.CreateModel(
            name='GardenManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='website.garden')),
            ],
            options={
                'ordering': ['garden', 'name'],
            },
        ),
        migrations.AddField(
            model_name='garden',
            name='vegetation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to='website.vegetationtype'),
        ),
    ]
