# Generated by Django 5.1.1 on 2024-11-22 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_shapefile',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='website.site'),
        ),
    ]
