# Generated by Django 5.1.1 on 2024-11-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_document_is_shapefile_document_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='garden',
            old_name='active',
            new_name='is_active',
        ),
    ]
