# Generated by Django 5.1.1 on 2024-11-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_active_document_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.document')),
            ],
        ),
    ]
