# Generated by Django 5.1.1 on 2024-11-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_document_file_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='site',
            new_name='attached_to',
        ),
    ]
