# Generated by Django 5.1.1 on 2024-11-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencespace',
            name='name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
