# Generated by Django 5.1.1 on 2024-11-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_referencespace_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tilelayer', models.CharField(max_length=1500)),
                ('attribution', models.CharField(max_length=1500)),
                ('style', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='mapstyle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
