# Generated by Django 5.1.1 on 2024-11-24 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_mapstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataviz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.JSONField(null=True)),
                ('mapstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mapstyle')),
                ('shapefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.document')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.site')),
            ],
        ),
    ]
