# Generated by Django 5.1.1 on 2024-11-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_dataviz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='mapstyle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.mapstyle'),
        ),
    ]
