# Generated by Django 5.1.1 on 2024-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_dataviz_mapstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataviz',
            name='fill_opacity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataviz',
            name='line_width',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataviz',
            name='opacity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
