# Generated by Django 5.1.1 on 2024-11-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_dataviz_fill_opacity_dataviz_line_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='corridor',
            field=models.ForeignKey(blank=True, limit_choices_to={'doc_type': 8}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_site', to='website.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.IntegerField(choices=[(1, 'Existing stepping-stones'), (2, 'Corridor connectors'), (3, 'Transport'), (4, 'Possible stepping-stones'), (5, 'Context'), (6, 'Teaching resources'), (7, 'General document repository'), (8, 'Ecological corridor')], db_index=True),
        ),
    ]
