# Generated by Django 5.1.1 on 2024-12-29 10:27

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_site_corridor_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='logos', variations={'medium': (800, 600), 'thumbnail': (350, 350)}),
        ),
    ]
