# Generated by Django 5.1.1 on 2024-12-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='design',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
