# Generated by Django 5.1.1 on 2024-12-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_site_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='description',
        ),
        migrations.RemoveField(
            model_name='species',
            name='propagation_cutting',
        ),
        migrations.RemoveField(
            model_name='species',
            name='propagation_seed',
        ),
        migrations.CreateModel(
            name='SpeciesText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alternative_names', models.CharField(blank=True, max_length=255, null=True)),
                ('propagation_seed', models.TextField(blank=True, null=True)),
                ('propagation_cutting', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.language')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.species')),
            ],
        ),
    ]
