# Generated by Django 5.1.1 on 2024-12-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_species_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='alternative_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='propagation_cutting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='propagation_seed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
