# Generated by Django 5.1.1 on 2024-12-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_species_alternative_names_species_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='alternative_names',
        ),
    ]
