# Generated by Django 5.1.1 on 2024-12-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_species_alternative_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='common_name_af',
        ),
        migrations.RemoveField(
            model_name='species',
            name='common_name_xh',
        ),
        migrations.RemoveField(
            model_name='species',
            name='description',
        ),
        migrations.RemoveField(
            model_name='species',
            name='propagation_cutting',
        ),
        migrations.RemoveField(
            model_name='species',
            name='propagation_seed',
        ),
    ]
