# Generated by Django 5.1.1 on 2024-12-29 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_species_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='corridor',
            field=models.ForeignKey(blank=True, limit_choices_to={'doc_type': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_site', to='website.document'),
        ),
        migrations.AlterField(
            model_name='site',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.language'),
        ),
    ]
