# Generated by Django 5.1.1 on 2024-12-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_site_corridor_alter_site_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='temp_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
