# Generated by Django 5.1.1 on 2025-01-01 10:31

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_document_temp_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_inat',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='license_code',
            field=models.CharField(blank=True, choices=[('cc0', 'Creative Commons Zero (CC0)'), ('cc-by', 'Creative Commons Attribution (CC BY)'), ('cc-by-sa', 'Creative Commons Attribution-ShareAlike (CC BY-SA)'), ('cc-by-nc', 'Creative Commons Attribution-NonCommercial (CC BY-NC)'), ('cc-by-nc-sa', 'Creative Commons Attribution-NonCommercial-ShareAlike (CC BY-NC-SA)'), ('cc-by-nc-nd', 'Creative Commons Attribution-NonCommercial-NoDerivs (CC BY-NC-ND)'), ('cc-by-nd', 'Creative Commons Attribution-NoDerivs (CC BY-ND)'), ('all-rights-reserved', 'All Rights Reserved')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.CharField(choices=[('upload', 'Uploaded photo'), ('inaturalist', 'iNaturalist')], default='upload', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='photos', variations={'large': (1280, 1024), 'medium': (800, 600), 'thumbnail': (350, 350)}),
        ),
        migrations.AlterField(
            model_name='speciestext',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='website.species'),
        ),
    ]
