# Generated by Django 5.1.1 on 2025-01-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_photo_image_inat_photo_license_code_photo_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
