# Generated by Django 5.1.1 on 2025-01-01 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_species', to='website.photo'),
        ),
    ]
