# Generated by Django 5.1.1 on 2025-01-02 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_species_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetationtype',
            name='redlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.redlist'),
        ),
    ]
