# Generated by Django 5.1.1 on 2025-01-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_species_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
    ]
