# Generated by Django 5.1.1 on 2025-01-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_remove_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('STEPPING_STONES', 'Existing stepping-stones'), ('CONNECTORS', 'Corridor connectors'), ('TRANSPORT', 'Transport'), ('POTENTIAL', 'Possible stepping-stones'), ('CONTEXT', 'Context'), ('TEACHING', 'Teaching resources'), ('GENERAL', 'General document repository'), ('CORRIDOR', 'Ecological corridor'), ('SPECIES_LIST', 'Species lists')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
