# Generated by Django 5.1.1 on 2025-01-04 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_document_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesVegetationTypeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.attachment')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.species')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vegetationtype')),
            ],
        ),
    ]
