# Generated by Django 5.1.1 on 2025-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_speciesvegetationtypelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='site',
            field=models.ManyToManyField(blank=True, to='website.site'),
        ),
    ]
