# Generated by Django 5.1.1 on 2025-01-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_species_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='corridor',
            field=models.ForeignKey(blank=True, limit_choices_to={'doc_type': 'CORRIDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_site', to='website.document'),
        ),
    ]
