# Generated by Django 5.1.1 on 2025-01-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_site_corridor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='design',
            new_name='meta_data',
        ),
    ]
