# Generated by Django 5.1.1 on 2025-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_rename_design_site_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciestext',
            name='description_wikipedia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
