# Generated by Django 5.1.1 on 2025-01-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_speciestext_description_wikipedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciestext',
            name='summary_wikipedia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
