# Generated by Django 5.1.1 on 2025-01-09 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_speciestext_summary_wikipedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.site'),
            preserve_default=False,
        ),
    ]
