# Generated by Django 5.1.1 on 2025-01-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_garden_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='contact_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='contact_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='contact_phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
