# Generated by Django 5.1.1 on 2025-01-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_garden_contact_email_garden_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='location_file',
            field=models.FileField(null=True, upload_to='gardenlocations'),
        ),
    ]
