# Generated by Django 5.1.1 on 2025-01-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_garden_location_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
    ]
