# Generated by Django 5.1.1 on 2025-01-21 14:47

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_remove_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cover_image',
            field=stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='covers', variations={'medium': (900, 900), 'thumbnail': (500, 500)}),
        ),
    ]
