# Generated by Django 5.1.1 on 2025-01-21 14:53

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_document_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cover_image',
            field=stdimage.models.StdImageField(force_min_size=False, null=True, upload_to='covers', variations={'medium': (700, 700), 'thumbnail': (300, 300)}),
        ),
        migrations.AlterField(
            model_name='speciesvegetationtypelink',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='website.attachment'),
        ),
    ]
