# Generated by Django 5.1.1 on 2025-01-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_document_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesvegetationtypelink',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_links', to='website.species'),
        ),
    ]
