# Generated by Django 5.1.1 on 2025-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_alter_speciesvegetationtypelink_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='vegetation_types',
            field=models.ManyToManyField(blank=True, null=True, to='website.vegetationtype'),
        ),
    ]
