# Generated by Django 5.1.1 on 2025-02-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_site_vegetation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='vegetation_types',
            field=models.ManyToManyField(blank=True, to='website.vegetationtype'),
        ),
    ]
