# Generated by Django 5.1.6 on 2025-12-02 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_page_is_active_page_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='website.site'),
            preserve_default=False,
        ),
    ]
