# Generated by Django 5.1.6 on 2025-12-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_organization_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='photos',
            field=models.ManyToManyField(blank=True, to='website.photo'),
        ),
    ]
