# Generated by Django 5.1.6 on 2025-12-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_page_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationtype',
            name='site',
            field=models.ManyToManyField(to='website.site'),
        ),
    ]
