# Generated by Django 5.1.6 on 2025-12-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_vegetationtype_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetationtype',
            name='site',
        ),
    ]
