# Generated by Django 5.1.6 on 2025-12-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_remove_vegetationtype_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationtype',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.site'),
            preserve_default=False,
        ),
    ]
