# Generated by Django 5.1.6 on 2025-12-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_vegetationtype_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='vegetation_types_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_site_vegetation', to='website.document'),
        ),
        migrations.AlterField(
            model_name='site',
            name='corridor',
            field=models.ForeignKey(blank=True, limit_choices_to={'doc_type': 'CORRIDOR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_site', to='website.document'),
        ),
    ]
