# Generated by Django 5.1.6 on 2025-12-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0050_site_vegetation_types_map_alter_site_corridor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationtype',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
