# Generated by Django 5.1.6 on 2025-12-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0051_vegetationtype_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Regular page'), (2, 'Blog entry')], db_index=True, default=1),
        ),
    ]
