# Generated by Django 5.1.6 on 2025-12-06 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0052_page_date_page_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_photos', to='website.referencespace'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Regular page'), (2, 'Blog'), (3, 'Event')], db_index=True, default=1),
        ),
    ]
