# Generated by Django 5.1.6 on 2025-12-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_photo_space_alter_page_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='space',
        ),
    ]
