# Generated by Django 5.1.6 on 2025-12-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_remove_photo_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencespace',
            name='photo',
        ),
    ]
