# Generated by Django 5.1.6 on 2025-12-10 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0055_remove_referencespace_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garden',
            name='is_user_created',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='garden',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
