# Generated by Django 5.1.6 on 2025-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0057_garden_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesfeatures',
            name='site',
            field=models.ManyToManyField(blank=True, to='website.site'),
        ),
    ]
