# Generated by Django 5.1.6 on 2025-12-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_speciesfeatures_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='features',
            field=models.ManyToManyField(blank=True, limit_choices_to={'site': models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='website.site')}, to='website.speciesfeatures'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Regular page'), (2, 'Blog'), (3, 'Event'), (4, 'Target species')], db_index=True, default=1),
        ),
    ]
