# Generated by Django 5.1.6 on 2025-12-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_page_features_alter_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='features',
            field=models.ManyToManyField(blank=True, to='website.speciesfeatures'),
        ),
    ]
