# Generated by Django 5.1.6 on 2025-12-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_page_created_at_page_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
