# Generated by Django 5.1.6 on 2025-12-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_alter_page_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='targets',
            field=models.ManyToManyField(blank=True, to='website.speciesfeatures'),
        ),
    ]
