# Generated by Django 5.1.6 on 2025-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_garden_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='targets',
            field=models.ManyToManyField(blank=True, to='website.page'),
        ),
    ]
