# Generated by Django 5.1.6 on 2025-12-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_alter_garden_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='site_features',
            field=models.ManyToManyField(blank=True, related_name='garden_site_features', to='website.page'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='garden_targets', to='website.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Regular page'), (2, 'Blog'), (3, 'Event'), (4, 'Target species'), (5, 'Site features')], db_index=True, default=1),
        ),
    ]
