# Generated by Django 5.1.6 on 2025-12-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0065_garden_site_features_alter_garden_targets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Currently present'), ('FUTURE', 'Future wish-list')], db_index=True, max_length=10)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.garden')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.species')),
            ],
        ),
    ]
