# Generated by Django 5.1.6 on 2025-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0066_gardenspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesfeatures',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter all the classes we need to add to the <i> tag', max_length=50, null=True),
        ),
    ]
