# Generated by Django 5.1.6 on 2025-12-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0067_speciesfeatures_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesfeatures',
            options={'ordering': ['species_type', 'name']},
        ),
    ]
