# Generated by Django 5.1.6 on 2025-12-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0068_alter_speciesfeatures_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenspecies',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='website.garden'),
        ),
        migrations.AlterField(
            model_name='gardenspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to='website.species'),
        ),
        migrations.AlterUniqueTogether(
            name='gardenspecies',
            unique_together={('garden', 'species')},
        ),
    ]
