# Generated by Django 5.1.6 on 2025-12-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0069_alter_gardenspecies_garden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesfeatures',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
