# Generated by Django 5.1.6 on 2025-12-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_speciesfeatures_icon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesfeatures',
            name='species_type',
            field=models.IntegerField(choices=[(5, 'Habitats & soils'), (1, 'Animal-friendly'), (2, 'Tolerances & suitability'), (3, 'Growth features'), (4, 'Social features')], db_index=True, default=0),
        ),
    ]
