# Generated by Django 5.1.6 on 2025-12-16 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_documentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('features', models.ManyToManyField(blank=True, related_name='log', to='website.speciesfeatures')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.attachment')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.species')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentLog',
        ),
    ]
