# Generated by Django 5.1.6 on 2025-12-16 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_filelog_delete_documentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(db_index=True, max_length=2, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='plant_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.plantform'),
        ),
    ]
