# Generated by Django 5.1.6 on 2025-12-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0075_plantform_species_plant_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='plant_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='website.plantform'),
        ),
    ]
