# Generated by Django 5.1.6 on 2025-12-16 12:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0076_alter_species_plant_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Color HTML code or name', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='flowering',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='species',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='species', to='website.color'),
        ),
    ]
