# Generated by Django 5.1.6 on 2025-12-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_color_species_flowering_species_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name']},
        ),
    ]
