# Generated by Django 5.1.6 on 2025-12-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0078_alter_color_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesfeatures',
            options={'ordering': ['species_type', 'icon', 'icon_svg', 'name']},
        ),
        migrations.AddField(
            model_name='page',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
