# Generated by Django 5.1.6 on 2025-12-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0079_alter_speciesfeatures_options_page_meta_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position', 'name']},
        ),
    ]
