# Generated by Django 5.1.6 on 2025-12-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0080_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Regular page'), (2, 'Blog'), (3, 'Event'), (4, 'Target species'), (5, 'Site features'), (6, 'Nursery'), (7, 'Blurb')], db_index=True, default=1),
        ),
    ]
