# Generated by Django 5.1.6 on 2025-12-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0081_alter_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
