# Generated by Django 5.1.6 on 2025-12-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0083_filelog_user_alter_filelog_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('STEPPING_STONES', 'Existing stepping-stones'), ('CONNECTORS', 'Corridor connectors'), ('TRANSPORT', 'Transport'), ('POTENTIAL', 'Possible stepping-stones'), ('CONTEXT', 'Context'), ('TEACHING', 'Teaching resources'), ('LINK', 'Links'), ('GENERAL', 'General document repository'), ('CORRIDOR', 'Ecological corridor'), ('SPECIES_LIST', 'Species lists')], db_index=True, default='GENERAL', max_length=20),
        ),
    ]
