# Generated by Django 5.1.6 on 2025-12-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0084_alter_document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationtype',
            name='is_negative',
            field=models.BooleanField(default=False, help_text='Indicates that this is e.g. alien / invasive vegetation'),
        ),
    ]
