# Generated by Django 5.1.6 on 2025-12-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0085_vegetationtype_is_negative'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vegetationtype',
            options={'ordering': ['is_negative', 'name']},
        ),
    ]
