# Generated by Django 6.0 on 2025-12-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0086_alter_vegetationtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='colors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filelog',
            name='flowering',
            field=models.BooleanField(default=False),
        ),
    ]
