# Generated by Django 6.0 on 2026-01-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0087_filelog_colors_filelog_flowering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelog',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='website.attachment'),
        ),
    ]
