# Generated by Django 6.0 on 2026-01-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0089_alter_speciesfeatures_species_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesfeatures',
            name='species_type',
            field=models.IntegerField(choices=[(5, 'Habitats & soils'), (1, 'Animal-friendly'), (2, 'Tolerances & suitability'), (3, 'Growth features'), (4, 'Social features'), (6, 'Aspect'), (7, 'Plant type')], db_index=True, default=0),
        ),
    ]
