# Generated by Django 6.0 on 2026-01-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_alter_speciesfeatures_species_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesfeatures',
            name='site',
            field=models.ManyToManyField(blank=True, related_name='features', to='website.site'),
        ),
    ]
