# Generated by Django 6.0 on 2026-01-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0092_alter_speciesfeatures_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='plant_form',
        ),
        migrations.DeleteModel(
            name='PlantForm',
        ),
    ]
