# Generated by Django 6.0 on 2026-01-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_featurenumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.speciesfeatures')),
                ('vegetation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='website.vegetationtype')),
            ],
        ),
        migrations.DeleteModel(
            name='FeatureNumbers',
        ),
    ]
