# Generated by Django 6.0 on 2026-01-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0095_featurecriteria_delete_featurenumbers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeatureCriteria',
            new_name='DiversityCriteria',
        ),
    ]
