# Generated by Django 6.0 on 2026-01-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0096_rename_featurecriteria_diversitycriteria'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diversitycriteria',
            constraint=models.UniqueConstraint(fields=('feature', 'vegetation_type'), name='unique_combo'),
        ),
    ]
