# Generated by Django 6.0 on 2026-01-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0097_diversitycriteria_unique_combo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diversitycriteria',
            options={'ordering': ['vegetation_type', 'feature__species_type', 'feature__name']},
        ),
        migrations.AddField(
            model_name='vegetationtype',
            name='minimum_species',
            field=models.SmallIntegerField(blank=True, help_text='The minimum number of species needed for a top-score (positive veg. type)', null=True),
        ),
        migrations.AddField(
            model_name='vegetationtype',
            name='negative_points',
            field=models.SmallIntegerField(blank=True, help_text='The number of negative point for each species in the garden (negative veg. type)', null=True),
        ),
    ]
