# Generated by Django 6.0 on 2026-01-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0098_alter_diversitycriteria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetationtype',
            name='minimum_species',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The minimum number of species needed for a top-score (positive veg. type)', null=True),
        ),
    ]
