# Generated by Django 6.0 on 2026-01-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0099_alter_vegetationtype_minimum_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetationtype',
            name='is_negative',
            field=models.BooleanField(db_index=True, default=False, help_text='Indicates that this is e.g. alien / invasive vegetation'),
        ),
        migrations.AlterField(
            model_name='vegetationtype',
            name='minimum_species',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='The minimum number of species needed for a top-score (positive veg. type)', null=True),
        ),
        migrations.AlterField(
            model_name='vegetationtype',
            name='negative_points',
            field=models.SmallIntegerField(blank=True, db_index=True, help_text='The number of negative point for each species in the garden (negative veg. type)', null=True),
        ),
    ]
