# Generated by Django 6.0 on 2026-01-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0100_alter_vegetationtype_is_negative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='vegetation_types',
        ),
        migrations.AlterField(
            model_name='vegetationtype',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_types', to='website.site'),
        ),
    ]
