# Generated by Django 6.0 on 2026-01-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0101_remove_site_vegetation_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='species',
            field=models.ManyToManyField(to='website.species'),
        ),
    ]
