# Generated by Django 6.0 on 2026-01-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0102_page_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardeningActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='website.site')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255, null=True)),
                ('intensity', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='website.gardeningactivity')),
            ],
        ),
    ]
