# Generated by Django 6.0 on 2026-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0103_gardeningactivity_activitycalendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gardeningactivity',
            options={'ordering': ['position', 'name']},
        ),
        migrations.AlterField(
            model_name='activitycalendar',
            name='intensity',
            field=models.IntegerField(choices=[(0, 'No activity'), (1, 'Low activity'), (2, 'Medium activity'), (3, 'High activity')], db_index=True),
        ),
    ]
