# Generated by Django 6.0 on 2026-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0104_alter_gardeningactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycalendar',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')]),
        ),
    ]
