# Generated by Django 6.0 on 2026-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0105_alter_activitycalendar_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesfeatures',
            name='species_type',
            field=models.IntegerField(choices=[(1, 'Wildlife supported'), (2, 'Tolerances & suitability'), (3, 'Growth features'), (4, 'Social features'), (5, 'Habitats'), (6, 'Aspect'), (7, 'Plant types'), (8, 'Succession'), (9, 'Soils')], db_index=True, default=0),
        ),
    ]
