# Generated by Django 6.0 on 2026-03-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0107_inventoryunit_nurseryinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseryinventory',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.inventoryunit'),
        ),
    ]
