# Generated by Django 6.0 on 2026-04-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0109_garden_garden_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='garden_type',
            field=models.IntegerField(choices=[(1, 'Public space'), (2, 'Private garden'), (3, 'Corporate garden/space'), (4, 'Balcony garden'), (99, 'Other')], db_index=True, default=1),
        ),
    ]
