# Generated by Django 6.0 on 2026-04-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0110_alter_garden_garden_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='languages_species',
            field=models.ManyToManyField(related_name='site_species', to='website.language'),
        ),
    ]
