# Generated by Django 6.0 on 2026-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0111_site_languages_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='lexicon_code',
            field=models.CharField(help_text='Lexicon code in iNaturalist', max_length=30, null=True),
        ),
    ]
