# Generated by Django 6.0 on 2026-05-04 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0112_language_lexicon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
