# Generated by Django 6.0 on 2026-05-06 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0113_emailquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseryinventory',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='website.species'),
        ),
    ]
