# Generated by Django 6.0 on 2026-05-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0114_alter_nurseryinventory_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryinventory',
            name='in_stock',
            field=models.BooleanField(db_index=True, null=True),
        ),
    ]
