# Generated by Django 6.0 on 2026-05-18 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0116_alter_speciesfeatures_species_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciesfeatures',
            name='site',
            field=models.ManyToManyField(blank=True, to='website.site'),
        ),
        migrations.CreateModel(
            name='FeatureSiteScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(db_index=True, default=1)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.site')),
            ],
        ),
    ]
