# Generated by Django 6.0 on 2026-05-18 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0117_alter_speciesfeatures_site_featuresitescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresitescore',
            name='feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='website.speciesfeatures'),
            preserve_default=False,
        ),
    ]
