# Generated by Django 6.0 on 2026-05-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0118_featuresitescore_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesfeatures',
            name='site',
        ),
    ]
