# Generated by Django 6.0 on 2026-05-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0119_remove_speciesfeatures_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesfeatures',
            name='site',
            field=models.ManyToManyField(blank=True, through='website.FeatureSiteScore', to='website.site'),
        ),
    ]
