# Generated by Django 6.0 on 2026-05-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0120_speciesfeatures_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresitescore',
            name='points',
            field=models.SmallIntegerField(db_index=True, default=1),
        ),
    ]
