# Generated by Django 6.0 on 2026-05-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0121_alter_featuresitescore_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Rank species using these automatic filters', related_name='defaults_for_site', to='website.speciesfeatures'),
        ),
        migrations.AlterField(
            model_name='featuresitescore',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.site'),
        ),
    ]
