# Generated by Django 6.0 on 2026-05-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0122_site_features_alter_featuresitescore_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetationtype',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.speciesfeatures'),
        ),
    ]
