# Generated by Django 6.0 on 2026-05-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0123_vegetationtype_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Regular page'), (2, 'Blog'), (3, 'Event'), (4, 'Garden targets'), (5, 'Garden features'), (6, 'Nursery'), (7, 'Blurb')], db_index=True, default=1),
        ),
    ]
