# Generated by Django 6.0 on 2026-05-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0124_alter_page_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='site_features',
            field=models.ManyToManyField(blank=True, limit_choices_to={'page_type': 5}, related_name='garden_site_features', to='website.page'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='targets',
            field=models.ManyToManyField(blank=True, limit_choices_to={'page_type': 4}, related_name='garden_targets', to='website.page'),
        ),
    ]
