# Generated by Django 6.0 on 2026-05-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0125_alter_garden_site_features_alter_garden_targets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciesfeatures',
            options={'ordering': ['species_type', 'name']},
        ),
    ]
