# Generated by Django 6.0 on 2026-05-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0126_alter_speciesfeatures_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Select the colors that should be shown on the search page', to='website.color'),
        ),
    ]
