# Generated by Django 6.0 on 2026-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0128_speciessynonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciessynonym',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
