# Generated by Django 6.0 on 2026-05-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0129_alter_speciessynonym_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
