# Generated by Django 6.0 on 2026-05-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0130_garden_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='garden_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='This is set upon activation, always +1 from the previous garden that was activated', null=True),
        ),
    ]
